POST http://localhost:3000/create/empresa/NVDA

# Create empresa,
# should return message with
#  - success message
#  - data of the company created and historical data created

/*
Create empresa,
should return message with
 - success message
 - data of the company created and historical data created
*/